apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: HOMEPAGE_TITLE
          value: "My Homelab"
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "home,home.bh.zz,10.0.20.50,10.0.20.50:30080,localhost,127.0.0.1"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homepage-config

