apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: '>=0.3.0'
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system

  # Pull tunnel secret from Kubernetes secret
  valuesFrom:
  - kind: Secret
    name: cloudflared-token
    valuesKey: token
    targetPath: cloudflare.secret

  values:
    replicaCount: 2

    # Use GHCR mirror to avoid Docker Hub CDN DNS issues
    image:
      repository: ghcr.io/crazy-max/cloudflared
      tag: "latest"

    cloudflare:
      account: "e21d62228b2de626a386eb1ed69292f5"
      tunnelId: "c4e17a2d-cdb2-4efb-ace9-682a6aa4304d"
      tunnelName: "homelab-k8s"

      # Ingress rules - what services to expose through the tunnel
      # Note: Helm chart automatically adds catch-all rule
      ingress:
        # Expose Silverbullet
        - hostname: sb.jlmitra.com
          service: http://silverbullet.silverbullet.svc.cluster.local:80

        # Expose Authelia authentication portal
        - hostname: auth.jlmitra.com
          service: http://authelia-svc.authelia.svc.cluster.local:9091
