apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: '>=0.3.0'
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system

  # Pull token from secret (created manually above)
  valuesFrom:
  - kind: Secret
    name: cloudflared-token
    valuesKey: token
    targetPath: cloudflare.token

  # Additional values (optional)
  values:
    replicaCount: 2
