apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: homepage
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homepage
  policy:
    semver:
      range: 1.x.x
  filterTags:
    pattern: '^v(?P<version>.*)$'
    extract: '$version'
